### PR TITLE
CERT_UNTRUSTED

### PR DESCRIPTION
**Pull request by Helldemon2017**
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.4.0-138-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pm2" "-g"
npm ERR! cwd /home/panda/node
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/panda/node/npm-debug.log
npm ERR! not ok code 0

### CODE REVIEW

**Comment by geraldz** [comment]
646 silly lockFile 5a14aa62-emoji-mart-vue-2-6-3 emoji-mart-vue@^2.6.3
647 silly lockFile 5a14aa62-emoji-mart-vue-2-6-3 emoji-mart-vue@^2.6.3
648 error Error: CERT_UNTRUSTED
648 error     at SecurePair.<anonymous> (tls.js:1370:32)
648 error     at SecurePair.EventEmitter.emit (events.js:92:17)
648 error     at SecurePair.maybeInitFinished (tls.js:982:10)
648 error     at CleartextStream.read [as _read] (tls.js:469:13)
648 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
648 error     at EncryptedStream.write [as _write] (tls.js:366:25)
648 error     at doWrite (_stream_writable.js:223:10)
648 error     at writeOrBuffer (_stream_writable.js:213:5)
648 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
648 error     at write (_stream_readable.js:583:24)
648 error     at flow (_stream_readable.js:592:7)
648 error     at Socket.pipeOnReadable (_stream_readable.js:624:5)
649 error If you need help, you may report this log at:
649 error     <http://github.com/isaacs/npm/issues>
649 error or email it to:
649 error     <npm-@googlegroups.com>
650 error System Linux 3.13.0-164-generic
651 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
652 error cwd /home/gerald/Dappos
653 error node -v v0.10.25
654 error npm -v 1.3.10
655 verbose exit [ 1, true ]

**Comment by geraldz** [comment]
Still getting this error:
gerald@gerald-HP-Pavilion-dv5-Notebook-PC:~$ npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-164-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /home/gerald
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gerald/npm-debug.log
npm ERR! not ok code 0

**Comment by probeusr** [comment]
I run in similar issue:
heavydutyhost@ranger:/$ docker attach a8096cc2878c
npm http GET https://registry.npmjs.org/jade/1.11.0
npm http GET https://registry.npmjs.org/mocha/2.2.5
npm http GET https://registry.npmjs.org/express/3.11.0
npm http GET https://registry.npmjs.org/supertest/1.1.0
npm http GET https://registry.npmjs.org/supertest/1.1.0
npm http GET https://registry.npmjs.org/mocha/2.2.5
npm http GET https://registry.npmjs.org/jade/1.11.0
npm http GET https://registry.npmjs.org/express/3.11.0
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.10.0-35-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /src
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /src/npm-debug.log
npm ERR! not ok code 0

**Comment by BatzuBatzu** [comment]
Hey there, im new on github. I want to install pimatic but got this errormessage:


pi@raspberrypi:/usr/local $ /usr/bin/env node --version
v0.10.24

pi@raspberrypi:/usr/local $ cd /home/pi

pi@raspberrypi:~ $ mkdir pimatic-app

pi@raspberrypi:~ $ npm install pimatic --prefix pimatic-app --production
npm http GET https://registry.npmjs.org/pimatic
npm http GET https://registry.npmjs.org/pimatic
npm http GET https://registry.npmjs.org/pimatic
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:221:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:211:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.19.75-v7l+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic" "--prefix" "pimatic-app" "--production"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0



Can you please tell me step by step what i have to install or to change so pimatic will run?!
BG

**Pull request closed without merging**
